services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=mamdaero
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/data/db/mysql:/var/lib/mysql
    networks:
      - internal_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internal_network

  spring:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    container_name: spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mamdaero?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - internal_network

  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    restart: always
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=9090 --prefix=/jenkins
    volumes:
      - /home/ubuntu/data/jenkins:/var/jenkins_home
    networks:
      - internal_network

networks:
  internal_network: